# Generated by Django 5.1.1 on 2024-09-30 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='archived_posts',
            field=models.ManyToManyField(blank=True, related_name='archived_by', to='blog.post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='read_posts',
            field=models.ManyToManyField(blank=True, related_name='read_by', to='blog.post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
